version: '3.8'

networks:
     dev:

services:
 app:
  container_name: dg-service
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - 8080:8080
   - 8090:8090
  networks:
   - dev
  depends_on:
   - postgres

 postgres:
  image: postgres:12-alpine
  restart: always
  container_name:  dg-database
  ports:
   - 5432:5432
  environment:
   POSTGRES_PASSWORD: 1
   POSTGRES_DB: data_generator
  networks:
   - dev







