server:
  port: 8080
  servlet:
    context-path: /generator-service
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        exclude: all
  endpoint:
    shutdown:
      enabled: true
