spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 8080
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        exclude: all
  endpoint:
    shutdown:
      enabled: true




